#!/usr/bin/env bash

cleanup() {
    rm -f "$bin/update-links"
}

set -eEu -o pipefail
cd "${0%/*}" || exit 1
today=$(date +%Y%m%d)

case "$1" in
    "")
        echo "You must specify a project to build or use 'all' to build everything." >&2
        exit 1
        ;;

    all)
        ./build builder

        for shellBinaryDir in ../*/bin; do
            shell=${shellBinaryDir%/*}
            shell=${shell##*/}
            ./build "$shell"
        done

        ./build multishell
        ;;

    builder)
        echo "*********** $1"
        cd "$1" || exit
        image=fidian/multishell-builder
        docker build -t "$image:latest" -t "$image:$today" -f Dockerfile .
        ;;

    multishell)
        echo "*********** $1"
        cd "$1" || exit
        image=fidian/multishell
        docker build -t "$image:latest" -t "$image:$today" -f Dockerfile .
        ;;

    *)
        echo "*********** $1"
        if [[ ! -d "../$1/bin" ]]; then
            echo "No such shell: $1" >&2
            exit 1
        fi

        bin="../$1/bin"
        scripts="../scripts"
        image="fidian/multishell-$1"

        trap cleanup EXIT
        cp "$scripts/update-links" "$bin"
        docker build -t "$image:latest" -t "$image:$today" -f generic/Dockerfile "$bin"
        ;;
esac
