#!/usr/bin/env bash

set -eEu -o pipefail
cd "${0%/*}" || exit 1
today=$(date +%Y%m%d)

case "${1-}" in
    "")
        echo "You must specify a project to build or use 'all' to build everything." >&2
        exit 1
        ;;

    all)
        ./build builder
        ./build scripts

        for shell in $(./list-shells); do
            ./build "$shell"
        done

        ./build small
        ./build multishell
        ;;

    builder | scripts | small)
        echo "*********** $1"
        image=fidian/multishell-"$1"
        docker build -t "$image:latest" -t "$image:$today" -f "$1/Dockerfile" "$1"
        ;;

    multishell)
        echo "*********** $1"
        image=fidian/multishell
        docker build -t "$image:latest" -t "$image:$today" -f "$1/Dockerfile" "$1"
        ;;

    *)
        echo "*********** $1"

        if [[ ! -d "../$1/bin" ]]; then
            echo "No such shell: $1" >&2
            exit 1
        fi

        bin="../$1/bin"
        image="fidian/multishell-$1"
        docker build -t "$image:latest" -t "$image:$today" -f generic/Dockerfile "$bin"
        ;;
esac
