#!/usr/bin/env bash
pushImage() {
    local tag

    echo
    echo "Pushing: $1:latest"
    echo
    docker push "$1:latest"
    tag=$(docker image list "$1" | awk '{print $2}' | grep -vE '^(TAG|latest|<none>)$' | sort -V | tail -n 1)
    echo
    echo "Pushing: $1:$tag"
    echo
    docker push "$1:$tag"
}


cd "${0%/*}" || exit 1

case "$1" in
    "")
        echo "You must specify a project to publish or use 'all' to publish everything." >&2
        exit 1
        ;;

    all)
        pushImage "fidian/multishell-builder"
        pushImage "fidian/multishell-scripts"

        for shell in $(./list-shells); do
            pushImage "fidian/multishell-$shell"
        done

        pushImage "fidian/multishell"
        pushImage "fidian/multishell-small"
        ;;

    multishell)
        pushImage fidian/multishell
        ;;

    *)
        pushImage "fidian/multishell-$1"
        ;;
esac
