#!/usr/bin/env bash
pushImage() {
    local tag

    echo
    echo "Pushing: $1"
    echo
    tag=$(docker image list "$1" | awk '{print $2}' | grep -vE '^(TAG|latest)$' | sort -V | tail -n 1)
    docker push "$1:latest"
    docker push "$1:$tag"
}


cd "${0%/*}" || exit 1

case "$1" in
    "")
        echo "You must specify a project to publish or use 'all' to publish everything." >&2
        exit 1
        ;;

    all)
        for shellDir in ../*/bin; do
            shell=${shellDir%/*}
            shell=${shell##*/}
            pushImage "fidian/multishell-$shell"
        done

        pushImage "fidian/multishell"
        pushImage "fidian/multishell-small"
        pushImage "fidian/multishell-builder"
        ;;

    multishell)
        pushImage fidian/multishell
        ;;

    *)
        pushImage "fidian/multishell-$1"
        ;;
esac
