#!/usr/bin/env bash

if [[ ! -d bin ]]; then
    mkdir bin
fi

if [[ ! -d git ]]; then
    git clone git@github.com:multishell/apple-bash.git git || git clone https://github.com/multishell/apple-bash.git git
fi
