#!/usr/bin/env bash

scriptName=${1:-}
containerName=${1:-interactive}-$$
multishellDir=$(cd "${0%/*}/.." && pwd 2> /dev/null)

# Run a docker container
cmd=(docker run)

# Limit the CPU, memory, swap, processes
cmd+=(--cpus 1 --memory 128M --memory-swap 0 --pids-limit 50)

# Set some names
cmd+=(--hostname "$name" --name "$containerName")

# Disallow changes, remove when done
cmd+=(--read-only --rm)

# Work in shared memory
cmd+=(--shm-size 64M --workdir /dev/shm)

# Set any temp directories
cmd+=(--tmpfs /tmp)

# Include Multishell as a bound volume
cmd+=(--volume "$multishellDir:/multishell:ro")

if [[ -z "$scriptName" ]]; then
    # Allocate a TTY and make this interactive
    cmd+=(--interactive --tty)
fi

# Change to the multishell directory
cmd+=(--workdir /multishell)

# Use the latest ubuntu image
cmd+=(fidian/multishell:latest)

# Run a shell
cmd+=(/bin/bash)

# Launch docker
"${cmd[@]}"
