#!/usr/bin/env bash

if [[ ! -d bin ]]; then
    mkdir bin
fi

if [[ ! -d git ]]; then
    git clone git@github.com:multishell/tcsh.git git || git clone https://github.com/multishell/tcsh.git git
fi

if [[ ! -d upstream ]]; then
    git clone https://github.com/tcsh-org/tcsh upstream
fi
