#!/usr/bin/env bash

if [[ ! -d bin ]]; then
    mkdir bin
fi

if [[ ! -d git ]]; then
    git clone git@github.com:multishell/fish.git git || git clone https://github.com/multishell/fish.git git
fi

if [[ ! -d upstream ]]; then
    git clone https://github.com/fish-shell/fish-shell.git upstream
fi
