#!/usr/bin/env bash

tryToBuild() {
    local ver

    ver=$1
    title "$ver: make (parallel)"
    make -j4 && return 0
    title "$ver: make (serial)"
    make && return 0

    return 1
}

title() {
    echo -n $'\E]2;'"$*"$'\E\\'
}

bulkBuild() {
    local ver

    ver=$1
    echo "Building version: $ver"
    (
        set -x
        cd git
        title "$ver: Clean"
        git clean -x -d -f || exit 1
        git checkout . || exit 1
        git checkout "ms_$ver" || exit 1

        if [[ -f autogen.sh ]]; then
            title "$ver: Autogen"
            ./autogen.sh
        else
            title "$ver: Autoreconf"
            touch NEWS README AUTHORS
            autoreconf --install
            ./configure
        fi

        title "$ver: Configure"
        ./configure || exit 1
        tryToBuild "$ver" || exit 1

        cd src
        strip dash || exit 1
        # shellcheck disable=SC2016
        saveVersion="../../bin/dash-${ver}"
        [[ ! -f "${saveVersion}" ]] || exit 1
        mv dash "${saveVersion}" || exit 1
    ) || {
        echo "Problem building version $ver"
        exit 1
    }
}

cd "${0%/*}" || exit 1

if [[ "$#" -gt 0 ]]; then
    for version in "$@"; do
        bulkBuild "$version" || exit
    done
else
    echo "Specify versions to build"
fi
